version: "3"
volumes:
  postgres-data:
    driver: local
services:
  master:
    image: redis:6.0.4
  slave:
    image: redis:6.0.4
    command: redis-server --slaveof redis-master 6379
    links:
      - master:redis-master
  sentinel_one:
    build: redis_sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_QUORUM=2
      - SENTINEL_PORT=26379
    links:
      - master:redis-master
      - slave
    ports:
      - "10001:26379"
  sentinel_two:
    build: redis_sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_QUORUM=2
      - SENTINEL_PORT=26379
    links:
      - master:redis-master
      - slave
    ports:
      - "10002:26379"
  sentinel_three:
    build: redis_sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
      - SENTINEL_QUORUM=2
      - SENTINEL_PORT=26379
    links:
      - master:redis-master
      - slave
    ports:
      - "10003:26379"
  db:
    image: postgres:10.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ankit
      POSTGRES_USER: ankit
    volumes:
      - postgres-data:/var/lib/postgresql/postdata
    depends_on:
      - master
      - slave
      - sentinel_one
      - sentinel_two
      - sentinel_three
  backend:
    build:
      context: ./SpringBoot_RedisSentinel_Client
    ports:
      - "8090:8090"
    links:
      - sentinel_one
      - sentinel_two
      - sentinel_three
    depends_on:
      - master
      - slave
      - sentinel_one
      - sentinel_two
      - sentinel_three
      - db
